## Colors ----------------------------

# Text Reset
Color_Off='\033[0m'

# Regular Colors
Black='\033[0;30m' Red='\033[0;31m' Green='\033[0;32m' Yellow='\033[0;33m'
Blue='\033[0;34m' Purple='\033[0;35m' Cyan='\033[0;36m' White='\033[0;37m'

## -----------------------------------

add_themes() {
  mkdir -p /usr/share/themes/
  cp -r /usr/share/berserk-arch/themes/ /usr/share/themes/
}

post_install() {
  add_themes
}

post_upgrade() {
  post_install
}
